export const kanjiData = {
  N5: [
    {
      id: "N5-K001",
      kanji: "日",
      onyomi: "ニチ・ジツ",
      kunyomi: "ひ・か",
      meaning: "Ngày, mặt trời",
      words: ["日本", "日曜日"],
    },
    {
      id: "N5-K002",
      kanji: "月",
      onyomi: "ゲツ・ガツ",
      kunyomi: "つき",
      meaning: "Tháng, mặt trăng",
      words: ["月曜日", "一月"],
    },
    {
      id: "N5-K003",
      kanji: "人",
      onyomi: "ジン・ニン",
      kunyomi: "ひと",
      meaning: "Người",
      words: ["日本人", "一人"],
    },
    {
      id: "N5-K004",
      kanji: "学",
      onyomi: "ガク",
      kunyomi: "まなぶ",
      meaning: "Học",
      words: ["学生", "学校"],
    },
    {
      id: "N5-K005",
      kanji: "校",
      onyomi: "コウ",
      kunyomi: "",
      meaning: "Trường",
      words: ["学校"],
    },
    {
      id: "N5-K006",
      kanji: "先",
      onyomi: "セン",
      kunyomi: "さき",
      meaning: "Trước",
      words: ["先生", "先週"],
    },
    {
      id: "N5-K007",
      kanji: "生",
      onyomi: "セイ・ショウ",
      kunyomi: "いきる",
      meaning: "Sinh, sống",
      words: ["学生", "先生"],
    },
    {
      id: "N5-K008",
      kanji: "山",
      onyomi: "サン",
      kunyomi: "やま",
      meaning: "Núi",
      words: ["山", "富士山"],
    },
    {
      id: "N5-K009",
      kanji: "川",
      onyomi: "セン",
      kunyomi: "かわ",
      meaning: "Sông",
      words: ["川"],
    },
    {
      id: "N5-K010",
      kanji: "田",
      onyomi: "デン",
      kunyomi: "た",
      meaning: "Ruộng",
      words: ["田中", "田"],
    },
  ],

  N4: [
    {
      id: "N4-K001",
      kanji: "旅",
      onyomi: "リョ",
      kunyomi: "たび",
      meaning: "Chuyến đi",
      words: ["旅行"],
    },
    {
      id: "N4-K002",
      kanji: "験",
      onyomi: "ケン",
      kunyomi: "",
      meaning: "Kiểm nghiệm, kinh nghiệm",
      words: ["経験"],
    },
    {
      id: "N4-K003",
      kanji: "理",
      onyomi: "リ",
      kunyomi: "",
      meaning: "Lý, nguyên lý",
      words: ["理由"],
    },
    {
      id: "N4-K004",
      kanji: "由",
      onyomi: "ユ・ユウ",
      kunyomi: "よし",
      meaning: "Do, lý do",
      words: ["理由"],
    },
    {
      id: "N4-K005",
      kanji: "健",
      onyomi: "ケン",
      kunyomi: "すこやか",
      meaning: "Khỏe",
      words: ["健康"],
    },
    {
      id: "N4-K006",
      kanji: "康",
      onyomi: "コウ",
      kunyomi: "",
      meaning: "Khỏe mạnh",
      words: ["健康"],
    },
  ],
};