export const vocabularyData = {
  N5: [
    {
      id: "N5-V001",
      word: "学校",
      kana: "がっこう",
      meaning: "Trường học",
      example: "学校へ行きます。",
      category: "Trường học",
    },
    {
      id: "N5-V002",
      word: "先生",
      kana: "せんせい",
      meaning: "Giáo viên",
      example: "先生は日本人です。",
      category: "Trường học",
    },
    {
      id: "N5-V003",
      word: "学生",
      kana: "がくせい",
      meaning: "Học sinh / sinh viên",
      example: "私は学生です。",
      category: "Trường học",
    },
    {
      id: "N5-V004",
      word: "友達",
      kana: "ともだち",
      meaning: "Bạn bè",
      example: "これは私の友達です。",
      category: "Quan hệ",
    },
    {
      id: "N5-V005",
      word: "日本",
      kana: "にほん",
      meaning: "Nhật Bản",
      example: "日本へ行きたいです。",
      category: "Địa điểm",
    },
    {
      id: "N5-V006",
      word: "今日",
      kana: "きょう",
      meaning: "Hôm nay",
      example: "今日は月曜日です。",
      category: "Thời gian",
    },
    {
      id: "N5-V007",
      word: "明日",
      kana: "あした",
      meaning: "Ngày mai",
      example: "明日は休みです。",
      category: "Thời gian",
    },
    {
      id: "N5-V008",
      word: "昨日",
      kana: "きのう",
      meaning: "Hôm qua",
      example: "昨日、学校へ行きました。",
      category: "Thời gian",
    },
    {
      id: "N5-V009",
      word: "食べます",
      kana: "たべます",
      meaning: "Ăn",
      example: "ごはんを食べます。",
      category: "Sinh hoạt",
    },
    {
      id: "N5-V010",
      word: "飲みます",
      kana: "のみます",
      meaning: "Uống",
      example: "水を飲みます。",
      category: "Sinh hoạt",
    },
    {
      id: "N5-V011",
      word: "行きます",
      kana: "いきます",
      meaning: "Đi",
      example: "学校へ行きます。",
      category: "Động từ",
    },
    {
      id: "N5-V012",
      word: "見ます",
      kana: "みます",
      meaning: "Xem / nhìn",
      example: "テレビを見ます。",
      category: "Động từ",
    },
  ],

  N4: [
    {
      id: "N4-V001",
      word: "経験",
      kana: "けいけん",
      meaning: "Kinh nghiệm",
      example: "日本で働いた経験があります。",
      category: "Kinh nghiệm",
    },
    {
      id: "N4-V002",
      word: "予定",
      kana: "よてい",
      meaning: "Dự định / kế hoạch",
      example: "明日の予定があります。",
      category: "Kế hoạch",
    },
    {
      id: "N4-V003",
      word: "必要",
      kana: "ひつよう",
      meaning: "Cần thiết",
      example: "これは必要です。",
      category: "Đời sống",
    },
    {
      id: "N4-V004",
      word: "理由",
      kana: "りゆう",
      meaning: "Lý do",
      example: "理由を説明してください。",
      category: "Giao tiếp",
    },
    {
      id: "N4-V005",
      word: "健康",
      kana: "けんこう",
      meaning: "Sức khỏe",
      example: "健康に気をつけています。",
      category: "Sức khỏe",
    },
    {
      id: "N4-V006",
      word: "旅行",
      kana: "りょこう",
      meaning: "Du lịch",
      example: "夏休みに旅行します。",
      category: "Du lịch",
    },
    {
      id: "N4-V007",
      word: "約束",
      kana: "やくそく",
      meaning: "Lời hứa / cuộc hẹn",
      example: "友達と約束があります。",
      category: "Giao tiếp",
    },
    {
      id: "N4-V008",
      word: "説明",
      kana: "せつめい",
      meaning: "Giải thích",
      example: "先生が説明します。",
      category: "Học tập",
    },
  ],
};